services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bakso_djaya_app
    restart: unless-stopped
    expose:
      - 3000
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      RESEND_API_KEY: ${RESEND_API_KEY}
      PROD_URL: ${PROD_URL}